version: "{build}"

skip_tags: true
test: off
max_jobs: 1

install:
  - cmd: SET MINGW_ZIP=i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z
  - cmd: IF NOT EXIST "%MINGW_ZIP%" curl -kLO "https://downloads.sourceforge.net/project/mingw-w64/Toolchains%%20targetting%%20Win32/Personal%%20Builds/mingw-builds/8.1.0/threads-posix/dwarf/%MINGW_ZIP%"
  - cmd: 7z x "%MINGW_ZIP%"
  - cmd: SET PATH=%APPVEYOR_BUILD_FOLDER%\mingw32\bin;%PATH%

cache:
  - i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z

before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3

build_script:
  - cmd: mingw32-make -j1 --keep-going

after_build:
  - cmd: cd deploy
  - cmd: COPY ..\README.md .
  - cmd: COPY ..\LICENSE .
  - cmd: 7z a ..\%APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_NUMBER%.7z .

artifacts:
  - path: $(appveyor_project_name)-$(appveyor_build_number).7z

deploy:
  - provider: Environment
    name: GH
    on:
      branch: master
